title: Toe Wai Lin
description: Full Stack Web Developer
show_downloads: true
google_analytics:
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  zip_url: https://github.com/toewailin/toewailin.github.io/raw/main/download.zip
  another_url: another value
  repository_url: https://github.com/toewailin/toewailin.github.io